ALTER TABLE app_settings
ADD COLUMN IF NOT EXISTS user_app_version TEXT NOT NULL DEFAULT '1.0.0',
ADD COLUMN IF NOT EXISTS user_app_url TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS driver_app_version TEXT NOT NULL DEFAULT '1.0.0',
ADD COLUMN IF NOT EXISTS driver_app_url TEXT DEFAULT '';
